version: '3'

services:
  
  flask:
    container_name: gl4-flask
    build: ./flask
    ports:
      - 5000:5000
    networks:
      - net
    depends_on:
      - redis
    env_file:
      - ./flask/.env

  redis:
    container_name: gl4-redis
    image: redis:alpine
    networks:
      - net

networks:
  net: